name: cucumber report
on:
  push:
    branches:
      - master

jobs:
  report-page:
    runs-on: ubuntu-16.04
    name: test a move of a cucumber report and the result for how to generate github pages

    steps:
      - uses: actions/checkout@v2
      - name: passed
        run: echo $(jq '.[].elements[].steps[].result.status' src/test/resources/cucumber.json | grep -c passed || true) > passed
      - name: failed
        run: echo $(jq '.[].elements[].steps[].result.status' src/test/resources/cucumber.json | grep -c failed || true) > failed
      - uses: navikt/bidrag-integration/cucumber-move@master
        with:
          folder_move_from: resources/generated-report
          front_page: front-page.md
          latest_cucumber_json: resources/cucumber.json
          project_where_to_move: bidrag-test-github-actions
      - run: |
          cd $RUNNER_WORKSPACE/bidrag-test-github-actions/docs/latest
          cat bidrag-dev.json

          TIMESTAMP=$( jq '.timestamp' bidrag-dev.json )
          FOLDER=$( jq '.foldername' bidrag-dev.json )

          if [[ -z $TIMESTAMP ]]; then
            exit 1
          fi

          echo "Timestamp: $TIMESTAMP"

          if [[ -z FOLDER ]]; then
            exit 1
          fi

          echo "Folder   : $FOLDER"
          echo ::set-output name=folder::$FOLDER
        id: json
      - uses: navikt/bidrag-integration/cucumber-latest@master
        id: report
        with:
          relative_filepath: docs/latest/cucumber.json
          json_path: '.[].elements[].steps[].result.status'
      - name: output results
        run: |
          ls -la
          export PASSED=${{ steps.report.outputs.steps_passed }}
          echo "Compare passed tests: $PASSED=$(cat passed)"

          if [[ $PASSED -ne $(cat passed) ]]; then
            exit 1;
          fi

          export FAILED=${{ steps.report.outputs.steps_failed }}
          echo "Compare failed tests: $FAILED=$(cat failed)"

          if [[ $FAILED -ne $(cat failed) ]]; then
            exit 1;
          fi
      - uses: navikt/bidrag-integration/cucumber-status@master
        id: status
        with:
          github_page: front-page.md
          passed: ${{ steps.report.outputs.steps_passed }}
          failed: ${{ steps.report.outputs.steps_failed }}
          timestamp: ${{ steps.report.outputs.time_moved }}
          project_name: bidrag-test-github-actions
          ghp_folder: docs
      - uses: navikt/bidrag-integration/reports@master
        with:
          pages_address: https://navikt.github.io/bidrag-test-github-actions
          path_github_page: ${{ steps.status.outputs.path_edited_page }}
      - name: check actions output from workflow
        run: |
          PATH_EDITED_PAGE=${{ steps.status.outputs.path_edited_page }}
          GENERATED_FOLDER=${{ steps.json.outputs.folder }}

          echo "edited page --- $( cat $PATH_EDITED_PAGE )"
          echo "generated folder : $GENERATED_FOLDER"

          if [ -z "$PATH_EDITED_PAGE" ]; then
            exit 1
          fi

          if [ -z "$GENERATED_FOLDER" ]; then
            exit 1
          fi
      - run: ls -al docs/generated
      - run: ls -al docs/generated/${{ steps.json.outputs.folder }}
      - run: ls -al docs/latest
