name: git commit workflow
on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-16.04
    name: test git commit action
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn -B -e release:update-versions
      - uses: navikt/bidrag-git/commit@feature-v3
        with:
          commit_message: bump version without author information
          pattern: pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mvn -B -e versions:set -DnewVersion=0.0.1-SNAPSHOT
      - uses: navikt/bidrag-git/commit@feature-v3
        with:
          author: tester
          commit_message: reset version with author information given
          pattern: pom.xml
          security_token: ${{ secrets.GITHUB_TOKEN }}
