name: test workflow with git commit
on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-16.04
    name: test git commit action
    steps:
      - uses: actions/checkout@v2
      - run: echo "test commit with author from github event" > a-file
      - run: ls -la && cat a-file
      - uses: navikt/bidrag-git/commit@v3
        with:
          commit_message: en test uten author oppgitt
          pattern: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "test commit with author" > another-file
      - run: ls -la && cat another-file
      - uses: navikt/bidrag-git/commit@feature-author
        with:
          author: tester
          commit_message: en test med author oppgitt
          pattern: .
          security_token: ${{ secrets.GITHUB_TOKEN }}
