name: docker workflow
on:
  push:
    branches:
      - master
      - feature-docker

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/bidrag-test-gh-actions:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-16.04
    name: build docker image

    steps:
      - name: Check if image manifest is available
        run: |
          REQUEST=$(curl --head --request GET "https://docker.pkg.github.com/v2/navikt/bidrag-test-github-actions/bidrag-test-gh-actio/manifests/$GITHUB_SHA" -u $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }})
          echo "
          Github head request statistics:
          ----
          $REQUEST
          "
      - uses: navikt/bidrag-docker/exists@master
        id: dockerimage
        with:
          image_name: bidrag-test-gh-actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo is docker image not found -> ${{ steps.dockerimage.outputs.not_found }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: navikt/bidrag-maven/setup@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mvn install -B -e -DskipTests=true
      - run: pwd && ls -al && cat Dockerfile
      - uses: navikt/bidrag-docker/build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  verify:
    runs-on: ubuntu-16.04
    name: verify docker image
    needs: build

    steps:
      - name: Check if image manifest is available
        run: |
          REQUEST=$(curl --head --request GET "https://docker.pkg.github.com/v2/navikt/bidrag-test-github-actions/bidrag-test-gh-actio/manifests/$GITHUB_SHA" -u $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }})
          echo "
          Github head request statistics:
          ----
          $REQUEST
          "
      - uses: navikt/bidrag-docker/exists@master
        id: dockerimage
        with:
          image_name: bidrag-test-gh-actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo is docker image not found -> ${{ steps.dockerimage.outputs.not_found }}
      - name: Fail when not found
        run: |
          if [ "$NOT_FOUND" == "true" ]; then
            exit 1;
          fi
        with:
          NOT_FOUND: ${{ steps.dockerimage.outputs.not_found }}
      - name: run when found
        if: {{ env.NOT_FOUND }} != 'true'
        run: echo found the docker image
        with:
          NOT_FOUND: ${{ steps.dockerimage.outputs.not_found }}

