name: test cucumber-clone action
on:
  push:
    branches:
      - feature/cucumber-clone

jobs:
  test:
    runs-on: ubuntu-16.04
    name: test cucumber-clone action

    steps:
      - uses: navikt/bidrag-integration/cucumber-clone@feature/clone-cucumber
      - name: verify cloned resources
        run: |
          cd $RUNNER_WORKSPACE
          ls -al
          [ -d bidrag-cucumber-backend ] || exit 1
          ls -al bidrag-cucumber-backend
          ls -al bidrag-cucumber-backend/simple
          [ -d bidrag-cucumber-backend/simple/bidrag-test-github-actions ] || exit 1
