name: test cucumber-clone action
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: test cucumber-clone action

    steps:
      - uses: navikt/bidrag-integration/cucumber-clone@main
      - name: verify cloned resources
        run: |
          set -x
          cd $RUNNER_WORKSPACE
          CLONED_FOLDER=$(find . -type f -name "pom.xml" | grep bidrag-cucumber-backend/pom.xml | sed 's;/pom.xml;;')

          ls -al
          [ -d "$CLONED_FOLDER" ] || exit 1
          ls -al "$CLONED_FOLDER"
          ls -al "$CLONED_FOLDER/apps"
          [ -d "$CLONED_FOLDER/apps/bidrag-test-github-actions" ] || exit 1
      - uses: navikt/bidrag-integration/cucumber-clone@main
        with:
          folder_nais_apps: alternativ
      - name: verify cloned resources with alternative folder
        run: |
          set -x
          cd $RUNNER_WORKSPACE
          CLONED_FOLDER=$(find . -type f -name "pom.xml" | grep bidrag-cucumber-backend/pom.xml | sed 's;/pom.xml;;')

          ls -al
          [ -d "$CLONED_FOLDER" ] || exit 1
          ls -al "$CLONED_FOLDER"
          ls -al "$CLONED_FOLDER/alternativ"
          [ -d "$CLONED_FOLDER/alternativ/bidrag-test-github-actions" ] || exit 1
