name: cucumber report
on:
  push:
    branches:
      - feature/gh-pages

jobs:
  report-page:
    runs-on: ubuntu-16.04
    name: parse json, count results with/without action and compare results

    steps:
      - uses: actions/checkout@v2
      - name: passed
        run: echo $(jq '.[].elements[].steps[].result.status' .github/resources/cucumber.json | grep -c passed || true) > passed
      - name: failed
        run: echo $(jq '.[].elements[].steps[].result.status' .github/resources/cucumber.json | grep -c failed || true) > failed
      - uses: navikt/bidrag-gh-pages/cucumber-move@feature/gh-pages
        with:
          folder_move_from: resources/generated-report
          front_page: front-page.md
          latest_cucumber_json: resources/cucumber.json
          project_where_to_move: bidrag-test-github-actions
      - uses: navikt/bidrag-gh-pages/cucumber-latest@master
        id: report
        with:
          relative_filepath: docs/latest/cucumber.json
          json_path: '.[].elements[].steps[].result.status'
      - name: output results
        run: |
          ls -la
          export PASSED=${{ steps.report.outputs.steps_passed }}
          echo "Compare passed tests: $PASSED=$(cat passed)"

          if [[ $PASSED -ne $(cat passed) ]]; then
            exit 1;
          fi

          export FAILED=${{ steps.report.outputs.steps_failed }}
          echo "Compare failed tests: $FAILED=$(cat failed)"

          if [[ $FAILED -ne $(cat failed) ]]; then
            exit 1;
          fi
      - uses: navikt/bidrag-gh-pages/cucumber-status@master
        id: status
        with:
          github_page: front-page.md
          passed: ${{ steps.report.outputs.steps_passed }}
          failed: ${{ steps.report.outputs.steps_failed }}
          project_name: bidrag-test-github-actions
          ghp_folder: docs
      - run: cat ${{ steps.status.outputs.edited_page }}
      - uses: navikt/bidrag-gh-pages/reports@master
        with:
          pages_address: https://navikt.github.io/bidrag-dev
          github_page_path: ${{ steps.status.outputs.edited_page }}
      - run: cat ${{ steps.status.outputs.edited_page }}
      - run: ls -al docs/generated
      - run: ls -al docs/latest
      - run: cat docs/latest/generated-report.html
