name: test use nais applications
on:
  push:
    branches:
      - feature/nais-apps

jobs:
  test-nais-apps:
    runs-on: ubuntu-16.04
    name: gh-pages nais applications

    steps:
      - uses: navikt/bidrag-gh-pages/cucumber-apps@feature/nais-apps
        id: apps
        with:
          nais-apps: '{"apps":["bidrag-hendelse-producer","bidrag-dokument-arkiv","bidrag-dokument"]}'
      - run: |
          cd "$NAIS_APPS_PATH"
          cd bidrag-hendelse-producer/nais
          [ -f q0.json ] || exit 1;
          [ -f q1.json ] || exit 1;
          cd ../../bidrag-dokument-arkiv/nais
          [ -f q0.json ] || exit 1;
          [ -f q1.json ] || exit 1;
          cd ../../bidrag-dokument/nais
          [ -f q0.json ] || exit 1;
          [ -f q1.json ] || exit 1;
        env:
          NAIS_APPS_PATH: ${{ steps.apps.output.nais-apps-folder }}
